### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'false'

### ISSUE THREAD

**Issue by mozeqiu** [PINTO0309/openvino2tensorflow#33] opened 2021-03-08 02:16 UTC
hello @PINTO0309 Thank you for sharing。When I started the conversion, the following error occurred,I have no idea.
setsopenvino2tensorflow
TensorFlow/Keras model building process starts ======================================
Traceback (most recent call last):
  File "/usr/local/bin/openvino2tensorflow", line 2433, in <module>
    main()
  File "/usr/local/bin/openvino2tensorflow", line 2429, in main
    yolact, weight_replacement_config, debug, debug_layer_number)
  File "/usr/local/bin/openvino2tensorflow", line 822, in convert
    antialias = False if int(data.attrib['antialias']) == 0 else True
ValueError: invalid literal for int() with base 10: 'false'

**Comment by PINTO0309** [comment] 2021-03-08 03:19
I know what the problem is and what the solution is. But can you provide a model for testing?

**Comment by mozeqiu** [comment] 2021-03-08 06:39
OK, I uploaded my Google cloud disk. This is my download link：
https://drive.google.com/file/d/1paH73FYxwmkA1RuTLHhCd1eOlO3uTqWf/view?usp=sharing

**Comment by PINTO0309** [comment] 2021-03-08 13:44
Instead of providing a converted model, please tell us.
Is the model you're trying to convert **`YOLOv5`**?

Due to the large number of garbage OPs, it is necessary to manually modify the .xml file before converting it.

- Converted Model - TFLite, pb, saved_model
**https://drive.google.com/file/d/1GYCjh8SVuwLwZCZFXesEDdx6Fl3aGZPD/view?usp=sharing**

The program has been modified and upgraded to **`v1.10.5`**. 094ac1d6147486325bfa6039408200c7fdddecf4

Please make sure to use the issue template in your next submission.

**Comment by mozeqiu** [comment] 2021-03-09 06:28
> 与其提供转换后的模型，请告诉我们。
> 您要转换的模型**`YOLOv5`**吗？
> 
> 由于大量垃圾OP，因此在转换.xml文件之前，有必要手动对其进行修改。
> 
> * 转换后的模型-TFLite，pb，保存的模型，自定义的OpenVINO IR 
>   **https://drive.google.com/file/d/1GYCjh8SVuwLwZCZFXesEDdx6Fl3aGZPD/view?usp=sharing**
> 
> 该程序已被修改并升级到**`v1.10.5`**。[094ac1d](https://github.com/PINTO0309/openvino2tensorflow/commit/094ac1d6147486325bfa6039408200c7fdddecf4)
> 
> 请确保在下一次提交中使用问题模板。
> 
> * model_float32.tflite
>   ![model_float32 tflite](https://user-images.githubusercontent.com/33194443/110332547-ccbd2e80-8063-11eb-9a39-fe37e29ada1b.png)

yes ,i  trying to convert YOLOv5!Im a  novice programmer and thanks very much for your help!

**Comment by PINTO0309** [comment] 2021-03-10 08:56
It looks like the problem has been solved, so close it.

**Closed by PINTO0309** 2021-03-10 08:56 UTC
Labels: bug, enhancement
