### ISSUE TITLE
The FakeQuantize layer is not yet implemented.

### ISSUE THREAD

**Issue by Gilberto-dev** [PINTO0309/openvino2tensorflow#13] opened 2021-01-17 13:17 UTC
Hy, 
I am trying to convert openvino model to tensorflow. But when I am doing it, it is throwing an error.

**[setupvars.sh] OpenVINO environment initialized
TensorFlow/Keras model building process starts ======================================
The FakeQuantize layer is not yet implemented.**

Conversion of that model is necessary. Please let me know if you can implement that layer or what is other workaround for this conversion. Thanks.

**Comment by PINTO0309** [comment] 2021-01-17 15:29
First, I have a request. If possible, could you please provide the .xml and .bin files and the .onnx or .pb or saved_model files to be converted? I need a minimum amount of materials to see if I can handle it.

**Comment by Gilberto-dev** [comment] 2021-01-18 04:48
Yeah sure. I am emailing you the files on this email ( rmsdh122@yahoo.co.jp ). Please let me know when you receive it.

**Comment by Gilberto-dev** [comment] 2021-01-20 04:43
Any Update ?

**Comment by PINTO0309** [comment] 2021-01-20 04:50
So far, as far as I know, the conversion from OpenVINO to other frameworks is difficult because I am the only one working on it. I have not seen any other engineer doing the same.

**Comment by QasimKhan5x** [comment] 2021-01-23 16:27
I'm facing the same issue with converting an OpenVino model to TensorFlow. I was working on a solution to this by implementing the FakeQuantize layer in the source code after following OpenVino [documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_ops_quantization_FakeQuantize_1.html). 

@PINTO0309 I'd like it if you could help me a little with implementation as I'm not so familiar with TensorFlow (Pytorch developer originally). 

So far, I have implemented the following code after line 1665 in [openvino2tensorflow.py](https://github.com/PINTO0309/openvino2tensorflow/blob/main/openvino2tensorflow/openvino2tensorflow.py#L1665):

    elif layer.attrib['type'] == 'FakeQuantize':
        x = tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 0)]
        x = tf.cast(x, dtype='float32')
        input_low = tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 1)]
        input_low = tf.cast(input_low, dtype='float32')
        input_high = tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 2)]
        input_high = tf.cast(input_high, dtype='float32')
        output_low = tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 3)]
        output_low = tf.cast(output_low, dtype='float32')
        output_high = tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 4)]
        output_high = tf.cast(output_high, dtype='float32')
        levels = int(data.attrib['levels'])
        
        tf_layers_dict[layer_id] = tf.where(tf.math.less_equal(x, tf.math.minimum(input_low, input_high)),
                                            output_low, tf.where(tf.math.greater(x, tf.math.maximum(input_low, input_high)),
                                            output_high,
                                            tf.math.round((x - input_low) / (input_high - input_low) * (levels-1)) / (levels-1) * (output_high - output_low) + output_low))

But I'm getting the following error when I try to convert my model:

    Traceback (most recent call last):
      File "openvino2tensorflow.py", line 2148, in <module>
        main()
      File "openvino2tensorflow.py", line 2144, in main
        yolact, debug, debug_layer_number)
      File "openvino2tensorflow.py", line 351, in convert
        kernel_initializer=Constant(tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 1)].transpose(2,3,1,0)))(tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 0)])
    AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'transpose'

Would appreciate your input on my code; thanks.

**Comment by PINTO0309** [comment] 2021-01-23 16:33
@QasimKhan5x 
Excellent. It's already midnight in Japan, so I'll check tomorrow. Thanks for your contribution!

**Comment by PINTO0309** [comment] 2021-01-24 06:04
@Gilberto-dev @QasimKhan5x 
FakeQuantize is implemented and committed. The version of the tool has been updated to v1.5.8. The conversion to Float32 appears to be successful, but I have no way to verify the veracity of the result, so I have no way of knowing if the conversion is correct.

Can you guys check the inference results to see if they are correct?

**Comment by QasimKhan5x** [comment] 2021-01-24 08:52
thank you @PINTO0309  the conversion has succeeded on my end

**Comment by Gilberto-dev** [comment] 2021-01-24 10:46
@PINTO0309 I am seeing model output channels are changed. from (1*2*513*513) to (1*513*2*513) and (1*513*513) to (1*513*2). What can be the possible issue. And when I am running inference it is outputting completely white image.

**Comment by QasimKhan5x** [comment] 2021-01-26 11:10
the inference results of the openvino model and the converted pb and tflite are quite different

**Comment by PINTO0309** [comment] 2021-01-26 11:24
@QasimKhan5x 
Is it possible to provide models (openvino/tflite) for validation and code (openvino/tflite) for validation?

**Comment by QasimKhan5x** [comment] 2021-01-26 11:42
Yes. I am emailing the OpenVino models (.xml and .bin), the .pb and .tflite files, as well as the code for inference to you.

**Comment by PINTO0309** [comment] 2021-02-07 08:08
@QasimKhan5x @Gilberto-dev
Some conversion bugs in FakeQuantize have been fixed.The latest version is v1.6.3. I don't think I can disclose the results here, so I will contact you individually. 

There is still a problem with accuracy, but it is much better now. Probably the rounding operation in the calculation process of FakeQuantize is not working properly.

If you want to change the behavior of Reshape and Transpose which are not needed, try removing the comments in the range below and run it. This will force the **`perm`** to be replaced and transformed correctly.
https://github.com/PINTO0309/openvino2tensorflow/blob/e0d168bfc8ba0343c3a031a7d5ef8f704d8c88ae/openvino2tensorflow/openvino2tensorflow.py#L324-L329

**Comment by Gilberto-dev** [comment] 2021-02-07 08:12
Thanks @PINTO0309 . @QasimKhan5x Please if you can check the inference results now with latest build.

**Comment by PINTO0309** [comment] 2021-02-07 08:22
@QasimKhan5x I sent the converted .tflite and .pb by email.

**Comment by Gilberto-dev** [comment] 2021-02-07 09:37
@PINTO0309 Thanks, the results are improved a lot. But one issue is I am seeing white borders around segmentation map, maybe because of issue you told above.  
` Probably the rounding operation in the calculation process of FakeQuantize is not working properly.`.
How can we solve that issue ?

**Comment by PINTO0309** [comment] 2021-02-07 10:23
@Gilberto-dev 
Since you have not provided me with any logic for inference testing, I have no idea what phenomenon you are talking about.

**Comment by PINTO0309** [comment] 2021-02-07 16:41
The version has been upgraded to v1.7.0. Enhancements have been made so that constants and weights such as Reshape and Transpose can be replaced by JSON.

**`--weight_replacement_config`** option.

Please read the README for details.

**Comment by QasimKhan5x** [comment] 2021-02-09 05:56
@PINTO0309 The inference with the model I have provided you earlier is working correctly. But when I use openvino2tensorflow.py to convert another OpenVino model, the reshape and transpose layers do not work as expected. 

Without editing the XML directly, is it possible to fix openvino2tensorflow.py so that conversion works properly?

**Comment by PINTO0309** [comment] 2021-02-09 06:37
@QasimKhan5x 

>Without editing the XML directly, is it possible to fix openvino2tensorflow.py so that conversion works properly?

Yes. 

>I see that the openvino2tensorflow.py file you provided me earlier contains hardcoded logic to correct the functionality of reshape and transpose.

The program has been modified so that it can compensate for Reshape and Transpose behavior without using hard-coded logic. Clone the latest program or use the pip command to update it. Currently, the latest version is v1.8.2. All hard-coded parts have been removed.

- clone
```
$ git clone https://github.com/PINTO0309/openvino2tensorflow.git
```
- pip
```
$ sudo pip3 install openvino2tensorflow --upgrade
```

>Or is it necessary to provide a JSON config file at this time?

In order to optimize the model to the limit, all logic is designed to assume **`NCHW`** outputs. On the other hand, operations that change the input geometry to **`NHWC`** format or inputs other than 4D tensors will not allow **`Reshape`** and **`Transpose`** to predict the correct converted geometry. Since it is difficult to automatically determine the output shape programmatically, I had no choice but to add a function to force the output shape to be changed in JSON.

Although it is tedious, please refer to the following procedure to adjust the output shape in JSON. 😢 
**https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op**

**Comment by QasimKhan5x** [comment] 2021-02-09 07:36
@PINTO0309 do I have to specify the layer of the Reshape/Tranpose or the layer of the Const that comes after a Reshape/Tranpose layer?

**Comment by QasimKhan5x** [comment] 2021-02-09 07:59
In my current model,
layer 1076 is a Reshape and layer 1077 is a Const. Both are sending output to layer 1078 which is a transpose. I have made a config file like this but layer 1078 is still getting wrong shape. 

![image](https://user-images.githubusercontent.com/29240497/107332843-801f1b80-6ad6-11eb-8cfb-e3b9bd14537e.png)

**Comment by PINTO0309** [comment] 2021-02-09 08:13
@QasimKhan5x 
Look at the <edges> listed at the end of the xml. Below is an image of the editor looking at the xml of a model that has a different structure than yours. If "1077" in the figure below is the Reshape layer, the input Const "layer_id" should be either "1075" or "1076".
![image](https://user-images.githubusercontent.com/33194443/107333483-e5840400-6af8-11eb-90e8-b6b8ba79e1b6.png)
In the example, if you need to replace the value of Const you will probably need to change the value of "1076" using JSON. "1075" is probably input from some other layer other than Const. The important thing to remember is that the "layer_id" of Const should at least be assigned an ID that is smaller and closer than Reshape or Transpose.

**Comment by QasimKhan5x** [comment] 2021-02-10 05:20
@PINTO0309 I am facing some issues even after following your instructions. As the issue is related to this feature and since the FakeQuantize layer issue has been solved, I am making a new issue for this.

**Comment by PINTO0309** [comment] 2021-02-10 10:12
@Gilberto-dev
QasimKhan5x says that it is able to convert the data with no problem. Please explain the details of the problem using images and other samples. I will close this issue once, so please post another issue if necessary.
**Reference issue: [openvino2tensorflow.py does not use provided values in weight configuration JSON #23](https://github.com/PINTO0309/openvino2tensorflow/issues/23)**

**Closed by PINTO0309** 2021-02-10 10:12 UTC
Labels: freature_request
